/**:
  ros__parameters:
    bus_names: [left_bus, right_bus]
    hand_names: [left, right]
    default_hand: left
    compat_single_hand_services: true

    buses:
      left_bus:
        type: canfd
        channel: 0
        canfd_arb_baudrate: 1000000
        canfd_data_baudrate: 5000000
        rs485_baudrate: 500000
      right_bus:
        type: canfd
        channel: 1
        canfd_arb_baudrate: 1000000
        canfd_data_baudrate: 5000000
        rs485_baudrate: 500000

    hands:
      left:
        bus: left_bus
        address: 1
        hand_type: LAC_DOF_6
      right:
        bus: right_bus
        address: 1
        hand_type: LAC_DOF_6
