#!/usr/bin/env python3
"""Create a vendor-specific hand_control source package."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "packaging" / "vendors.json"
DEFAULT_OUTPUT_DIR = ROOT / "dist"

MODELS_REL = Path("src/hand_control_description/models")
MODEL_CONFIG_REL = Path("src/hand_control_description/config/model.yaml")
THIRDPARTY_REL = Path("src/hand_control_service/thirdparty")
SDK_PROFILE_REL = Path("src/hand_control_service/config/sdk_profile.cmake")

EXCLUDED_ROOT_NAMES = {
    ".git",
    ".pytest_cache",
    "__pycache__",
    "build",
    "dist",
    "install",
    "log",
    "packaging",
}

EXCLUDED_ANYWHERE_NAMES = {
    ".pytest_cache",
    "__pycache__",
}

EXCLUDED_RELATIVE_FILES = {
    Path("AGENTS.md"),
    Path("scripts/package_vendor.py"),
}

EXCLUDED_RELATIVE_DIRS = {
    MODELS_REL,
    THIRDPARTY_REL,
}


def load_manifest(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def normalize_rel(path: Path) -> Path:
    return Path(*path.parts)


def should_exclude(path: Path) -> bool:
    rel = normalize_rel(path.relative_to(ROOT))
    if any(part in EXCLUDED_ANYWHERE_NAMES for part in rel.parts):
        return True
    if path.suffix == ".pyc":
        return True
    if len(rel.parts) == 1 and rel.parts[0] in EXCLUDED_ROOT_NAMES:
        return True
    if rel in EXCLUDED_RELATIVE_FILES:
        return True
    return any(rel == excluded or excluded in rel.parents for excluded in EXCLUDED_RELATIVE_DIRS)


def copy_workspace(staging_root: Path) -> None:
    for item in ROOT.iterdir():
        if should_exclude(item):
            continue
        destination = staging_root / item.name
        if item.is_dir():
            shutil.copytree(
                item,
                destination,
                symlinks=True,
                ignore=lambda current, names: [
                    name
                    for name in names
                    if should_exclude(Path(current) / name)
                ],
            )
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, destination)


def copy_required_directory(source: Path, destination: Path) -> None:
    if not source.is_dir():
        raise FileNotFoundError(f"Required directory not found: {source}")
    if destination.exists():
        shutil.rmtree(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source, destination, symlinks=True)


def copy_required_file(source: Path, destination: Path) -> None:
    if not source.is_file():
        raise FileNotFoundError(f"Required file not found: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def overlay_models(staging_root: Path, vendor: dict) -> None:
    source_models = ROOT / MODELS_REL
    target_models = staging_root / MODELS_REL
    target_models.mkdir(parents=True, exist_ok=True)
    for model_name in vendor["models"]:
        copy_required_directory(
            source_models / model_name,
            target_models / model_name,
        )


def overlay_thirdparty(staging_root: Path, vendor: dict) -> None:
    source_thirdparty = ROOT / THIRDPARTY_REL
    target_thirdparty = staging_root / THIRDPARTY_REL
    sdk = vendor["sdk"]

    copy_required_directory(
        source_thirdparty / "include" / sdk["include_dir"],
        target_thirdparty / "include" / sdk["include_dir"],
    )

    for lib_name in sdk["libs"]:
        copy_required_file(
            source_thirdparty / "lib" / lib_name,
            target_thirdparty / "lib" / lib_name,
        )

    for rel_dir in vendor.get("common_thirdparty_dirs", []):
        source = source_thirdparty / rel_dir
        if source.exists():
            copy_required_directory(source, target_thirdparty / rel_dir)

    for rel_dir in vendor.get("thirdparty_dirs", []):
        copy_required_directory(source_thirdparty / rel_dir, target_thirdparty / rel_dir)


def write_model_config(staging_root: Path, vendor: dict) -> None:
    content = (
        "# Generated by scripts/package_vendor.py.\n"
        "# If urdf_file is empty, launch resolves urdf/<active_model>.urdf first.\n"
        f"active_model: {vendor['active_model']}\n"
        "urdf_file:\n"
    )
    target = staging_root / MODEL_CONFIG_REL
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")


def write_sdk_profile(staging_root: Path, vendor: dict) -> None:
    sdk = vendor["sdk"]
    content = (
        "# Generated by scripts/package_vendor.py.\n"
        "\n"
        f'set(HC_SDK_LIB_NAME "{sdk["lib_name"]}")\n'
        f'set(HC_SDK_HEADER "{sdk["header"]}")\n'
        f'set(HC_SDK_NS "{sdk["namespace"]}")\n'
        f'set(HC_SDK_CLASS "{sdk["class"]}")\n'
    )
    target = staging_root / SDK_PROFILE_REL
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")


def lower_terms(terms: Iterable[str]) -> list[tuple[str, bytes]]:
    return [(term, term.lower().encode("utf-8")) for term in terms if term]


def scan_forbidden(staging_root: Path, terms: Iterable[str]) -> list[str]:
    forbidden = lower_terms(terms)
    findings: list[str] = []
    if not forbidden:
        return findings

    for path in staging_root.rglob("*"):
        rel = path.relative_to(staging_root).as_posix()
        lowered_rel = rel.lower().encode("utf-8")
        for term_text, term in forbidden:
            if term in lowered_rel:
                findings.append(f"path ({term_text}): {rel}")
                break
        if not path.is_file():
            continue
        try:
            data = path.read_bytes().lower()
        except OSError as exc:
            findings.append(f"unreadable: {rel}: {exc}")
            continue
        for term_text, term in forbidden:
            if term in data:
                findings.append(f"content ({term_text}): {rel}")
                break
    return findings


def strip_shared_libraries(staging_root: Path) -> None:
    strip_tool = shutil.which("strip") or shutil.which("llvm-strip")
    if not strip_tool:
        raise RuntimeError("--strip-libs requested, but neither strip nor llvm-strip was found")

    lib_dir = staging_root / THIRDPARTY_REL / "lib"
    for library in lib_dir.glob("*.so*"):
        subprocess.run(
            [strip_tool, "--strip-unneeded", str(library)],
            check=True,
        )


def make_zip(staging_root: Path, archive_path: Path) -> None:
    if archive_path.exists():
        archive_path.unlink()
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in staging_root.rglob("*"):
            if path.is_dir():
                continue
            archive.write(path, path.relative_to(staging_root.parent))


def safe_reset_dir(path: Path, output_dir: Path) -> None:
    resolved = path.resolve()
    output_root = output_dir.resolve()
    if output_root not in resolved.parents and resolved != output_root:
        raise RuntimeError(f"Refusing to remove path outside dist: {path}")
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def package_vendor(
    vendor_key: str,
    output_dir: Path,
    keep_staging: bool,
    strip_libs: bool,
    strict_scan: bool,
) -> Path:
    manifest = load_manifest(MANIFEST)
    vendors = manifest["vendors"]
    if vendor_key not in vendors:
        known = ", ".join(sorted(vendors))
        raise KeyError(f"Unknown vendor '{vendor_key}'. Known vendors: {known}")

    vendor = vendors[vendor_key]
    package_name = vendor["package_name"]
    staging_parent = output_dir / "_staging"
    staging_root = staging_parent / package_name
    archive_path = output_dir / f"{package_name}.zip"

    output_dir.mkdir(parents=True, exist_ok=True)
    safe_reset_dir(staging_root, output_dir)

    copy_workspace(staging_root)
    overlay_models(staging_root, vendor)
    overlay_thirdparty(staging_root, vendor)
    write_model_config(staging_root, vendor)
    write_sdk_profile(staging_root, vendor)

    if strip_libs:
        strip_shared_libraries(staging_root)

    findings = scan_forbidden(staging_root, vendor.get("forbidden", []))
    if findings:
        message = "\n".join(f"  - {finding}" for finding in findings[:50])
        more = "" if len(findings) <= 50 else f"\n  ... {len(findings) - 50} more"
        warning = (
            f"Forbidden strings found in staged package '{package_name}':\n"
            f"{message}{more}"
        )
        if strict_scan:
            raise RuntimeError(warning)
        print(f"Warning: {warning}", file=sys.stderr)

    make_zip(staging_root, archive_path)
    if not keep_staging:
        shutil.rmtree(staging_root)
        if staging_parent.exists() and not any(staging_parent.iterdir()):
            staging_parent.rmdir()
    return archive_path


def prompt_vendor(vendors: dict) -> str:
    vendor_keys = list(vendors.keys())
    print("Select vendor package:")
    for index, key in enumerate(vendor_keys, start=1):
        display_name = vendors[key].get("display_name", key)
        print(f"  {index}. {display_name} ({key})")

    while True:
        try:
            choice = input("Enter 1 or 2, or vendor key: ").strip()
        except EOFError as exc:
            raise RuntimeError("No vendor selected") from exc
        if not choice:
            continue
        if choice.isdigit():
            index = int(choice)
            if 1 <= index <= len(vendor_keys):
                return vendor_keys[index - 1]
        normalized = choice.lower()
        if normalized in vendors:
            return normalized
        print("Invalid selection. Please try again.")


def pause_if_interactive(interactive: bool) -> None:
    if interactive:
        try:
            input("Press Enter to exit...")
        except EOFError:
            pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a vendor-specific hand_control source zip."
    )
    parser.add_argument(
        "vendor",
        nargs="?",
        help="Vendor key from packaging/vendors.json. Omit to choose interactively.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for generated package artifacts",
    )
    parser.add_argument(
        "--keep-staging",
        action="store_true",
        help="Keep the staged source tree after zipping",
    )
    parser.add_argument(
        "--strip-libs",
        action="store_true",
        help="Run strip --strip-unneeded on packaged .so files before scanning",
    )
    parser.add_argument(
        "--strict-scan",
        action="store_true",
        help="Fail the package if forbidden vendor strings are found",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    pause_on_exit = args.vendor is None and sys.stdin.isatty()
    manifest = load_manifest(MANIFEST)
    vendors = manifest["vendors"]
    vendor_key = args.vendor or prompt_vendor(vendors)

    try:
        archive_path = package_vendor(
            vendor_key,
            args.output_dir,
            args.keep_staging,
            args.strip_libs,
            args.strict_scan,
        )
    except Exception as exc:
        print(f"package_vendor: {exc}", file=sys.stderr)
        pause_if_interactive(pause_on_exit)
        return 1

    print(f"Created package: {archive_path}")
    pause_if_interactive(pause_on_exit)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
